version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_packages.zip .
      - cd ..
      - zip -g deployment_packages.zip lambda_function.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_packages.zip s3://gds-lambda-build-code/ 
      - aws lambda update-function-code --function-name DoorDashDelivery-github-cicd-function --s3-bucket gds-lambda-build-code --s3-key deployment_packages.zip
      - echo "Deployment complete!"